import React from "react";
import { X, Shield, FileCheck, Lock, CheckCircle2, Award, Info } from "lucide-react";
import { AppLogo } from "./AppLogo";

interface TermsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const TermsModal: React.FC<TermsModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/60 backdrop-blur-sm animate-in fade-in duration-200">
      <div 
        className="bg-white w-full max-w-2xl max-h-[85vh] rounded-3xl shadow-2xl border border-slate-100 flex flex-col overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="p-6 border-b border-slate-100 flex items-center justify-between bg-slate-50/70">
          <div className="flex items-center gap-3">
            <AppLogo size="sm" showText={false} />
            <div>
              <h3 className="text-lg font-black text-slate-950 tracking-tight">Terms of Service & Privacy</h3>
              <p className="text-xs text-slate-500 font-medium">ClassFund Manager by Darryl Jay Castillo (SHIRO)</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 text-slate-400 hover:text-slate-700 hover:bg-slate-200/60 rounded-xl transition"
            aria-label="Close Terms modal"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Scrollable Content */}
        <div className="p-6 overflow-y-auto space-y-6 text-slate-600 text-xs sm:text-sm leading-relaxed">
          {/* Section 1 */}
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-slate-900 font-bold">
              <Shield className="h-4 w-4 text-emerald-600 shrink-0" />
              <h4>1. Acceptance & Purpose</h4>
            </div>
            <p className="text-slate-600">
              Welcome to <strong>ClassFund Manager</strong>, an official classroom financial transparency and student ledger platform. By accessing or creating an account as a Treasurer or Student, you agree to comply with these terms, dedicated to upholding total honesty, accurate reporting, and secure bookkeeping.
            </p>
          </div>

          {/* Section 2 */}
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-slate-900 font-bold">
              <FileCheck className="h-4 w-4 text-emerald-600 shrink-0" />
              <h4>2. Treasurer Responsibilities & Audit Logging</h4>
            </div>
            <p className="text-slate-600">
              Treasurers hold fiduciary responsibility for their classroom records. Every payment entry, fee target update, and recorded school expense is logged automatically into the tamper-resistant <strong>Firebase Firestore Audit Ledger</strong> with timestamps and user identifiers.
            </p>
          </div>

          {/* Section 3 */}
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-slate-900 font-bold">
              <Lock className="h-4 w-4 text-emerald-600 shrink-0" />
              <h4>3. Student Privacy & Data Security</h4>
            </div>
            <p className="text-slate-600">
              We respect student privacy. Student IDs, payment transaction histories, and digital receipts are accessible strictly to enrolled classroom members and designated officers. No personal student data is ever sold, distributed, or exposed to third-party marketing services.
            </p>
          </div>

          {/* Section 4 */}
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-slate-900 font-bold">
              <Award className="h-4 w-4 text-emerald-600 shrink-0" />
              <h4>4. Digital Receipts & Verification</h4>
            </div>
            <p className="text-slate-600">
              Receipts and QR code acknowledgments generated by ClassFund Manager serve as digital proof-of-payment records for institutional audits, department clearances, and classroom balancing.
            </p>
          </div>

          {/* Attribution Box */}
          <div className="p-4 bg-emerald-50/60 rounded-2xl border border-emerald-100 flex items-start gap-3">
            <Info className="h-5 w-5 text-emerald-600 shrink-0 mt-0.5" />
            <div className="text-xs text-emerald-900 leading-normal">
              <p className="font-bold">Original Creator & Lead Engineer</p>
              <p className="text-emerald-800">
                ClassFund Manager is created and designed by <strong>Darryl Jay Castillo (SHIRO)</strong>. All system architectures, secure audit protocols, and user interfaces are protected.
              </p>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-100 bg-slate-50 flex items-center justify-between">
          <div className="flex items-center gap-1.5 text-[11px] text-slate-400 font-medium">
            <CheckCircle2 className="h-3.5 w-3.5 text-emerald-600" />
            <span>Last Updated: August 2026</span>
          </div>
          <button
            onClick={onClose}
            className="px-5 py-2 bg-slate-950 hover:bg-slate-900 text-white font-bold text-xs rounded-xl shadow-sm transition cursor-pointer"
          >
            I Understand
          </button>
        </div>
      </div>
    </div>
  );
};
